signIn=async(email,password)=>{
  firebase
    .auth()
    .signInWithEmailAndPassword(email,password)
    .then(()=>{
      this.props.navigation.replace("Dashbroad");
    })
    .catch(error=>{
        Alert.alert(error.message);
    });
};
